// <auto-generated />
namespace SerwisKsiazkowy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Review_addRateValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Review_addRateValue));
        
        string IMigrationMetadata.Id
        {
            get { return "201905112022275_Review_addRateValue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
