// <auto-generated />
namespace SerwisKsiazkowy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rate_review : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rate_review));
        
        string IMigrationMetadata.Id
        {
            get { return "201905111844391_rate_review"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
